name: CI
on:
  workflow_call:
    inputs:
      PROJECT_NAME:
        required: true
        type: string
    secrets:
      GH_TOKEN:
        required: true
      NPM_REGISTRY_CREDENTIALS:
        required: true
jobs:
  ci:
    runs-on: ubuntu-22.04
    env:
      CI: True
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_TOKEN }}
      - name: Set @mundibot as committer
        run: |
          git config --global user.name "mundibot"
          git config --global user.email "tech@mundi.io"
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Set Release version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Print Release version
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.4.0
        with:
          credentials_json: '${{ secrets.NPM_REGISTRY_CREDENTIALS }}'
      - name: Login to Artifact Registry
        run: yarn run artifactregistry-login
      - run: yarn install --frozen-lockfile --ignore-scripts
      - name: Build packages.
        run: yarn run build
      - name: Running linter validation.
        run: yarn run lint
      - name: Running tests.
        run: yarn run test
      - run: echo "🍏 This job's status is ${{ job.status }}."
